# Generated by Django 3.0.2 on 2020-08-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('website', models.URLField(max_length=100, verbose_name='Company Website')),
                ('address', models.TextField(verbose_name='Company Address')),
                ('logo', models.FileField(upload_to='logo/')),
            ],
        ),
    ]
