# Generated by Django 3.0.2 on 2020-08-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Full Name')),
                ('slug', models.SlugField(max_length=250)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('job_role', models.CharField(max_length=100, verbose_name='Job Title')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone_no', models.CharField(max_length=15, verbose_name='Phone Numner')),
                ('profile', models.FileField(upload_to='profile/')),
            ],
        ),
    ]
