# Generated by Django 3.0.2 on 2020-08-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200809_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='color',
            field=models.CharField(default='#3F51B5', max_length=7),
        ),
    ]
