# Generated by Django 3.0.2 on 2020-08-09 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_company_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialmedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'Linkedin'), ('twitter', 'Twitter')], max_length=50)),
                ('link', models.URLField()),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='homepage.company')),
            ],
        ),
    ]
